# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weatherbly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'PinLayout'
    pod 'FlexLayout'
    pod 'Then'
    pod 'RxSwift', '~> 6.5.0'
    pod 'RxCocoa', '~> 6.5.0'
#    pod 'FSPagerView'
    pod 'UIViewBorders'

  # Pods for Weatherbly

end
