############# 변수 정의 ##############

$webhook_url_release = "" 
$webhook_url_test = ""

####################################

default_platform(:ios)
skip_docs
platform :ios do

error do |lane, exception, options|
	lane_remove_badge
	discord_notifier(
	    webhook_url: "#{webhook_url_test}",
	    title: "에러 발생",
	    description: "#{exception}",
	    success: false,
	    thumbnail_url:"",
	    image_url:""
	)
end

desc "Push a new release build to the App Store"
lane :release do
	version = get_version_number(
		xcodeproj: "Weatherbly.xcodeproj",
		target: "WeatherVely", 
		configuration: "Release"
	)
  	get_certificates
	get_provisioning_profile
	build_app(
		workspace: "Weatherbly.xcworkspace", 
		scheme: "WeatherVely",
		configuration: "Release"
	)
	  upload_to_app_store(
		app_version: version,
	    submit_for_review: true,
		force: true,
		automatic_release: true,
		skip_screenshots: true,
		skip_metadata: false
	)
	discord_notifier(
		webhook_url: "#{webhook_url_release}",
		title: "배포 성공",
		description: ""
	)
end

desc "Push a new beta build to TestFlight"
lane :beta do
  	get_certificates
  	get_provisioning_profile
  	build_app(
		workspace: "Weatherbly.xcworkspace", 
		scheme: "WeatherVely_test",
		configuration: "Debug"
	)
  	upload_to_testflight(
		skip_waiting_for_build_processing: true
	)
	discord_notifier(
		webhook_url: "#{webhook_url_test}",
		title: "배포 성공",
		description: ""
	)
end

end